//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.ORDEN = new HashSet<ORDEN>();
        }
    
        public string RUTCLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string DIRECCION { get; set; }
        public string PAIS { get; set; }
        [Display(Name = "CLIENTE")]
        public string TIPOCLIENTE { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name = "N° PROCESO")]
        public Nullable<decimal> PROCESOVENTA { get; set; }
    
        public virtual ICollection<ORDEN> ORDEN { get; set; }
        public virtual PROCESOVENTA PROCESOVENTA1 { get; set; }
    }
}
