//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.VENTA = new HashSet<VENTA>();
        }
    
        public string RUTEMPRESA { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
    
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
