//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        public ORDEN()
        {
            this.PAGO = new HashSet<PAGO>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
            this.SUBASTA = new HashSet<SUBASTA>();
        }
    
        public decimal IDORDEN { get; set; }
        public System.DateTime FECHA { get; set; }
        public string CLIENTE_RUTCLIENTE { get; set; }
        public string ESTADO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        public virtual ICollection<SUBASTA> SUBASTA { get; set; }
    }
}
