//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PROCESOVENTA
    {
        public PROCESOVENTA()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
            this.SUBASTA = new HashSet<SUBASTA>();
            this.VENTA = new HashSet<VENTA>();
        }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name ="N° PROCESO")]
        public decimal IDPROCESOVENTA { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime FECHA { get; set; }
        [Display(Name = "PROCESO VENTA")]
        public string TIPOPROCESO { get; set; }
        public Nullable<decimal> ORDENID { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ORDEN ORDEN { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        public virtual ICollection<SUBASTA> SUBASTA { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
