//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOR
    {
        public PRODUCTOR()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public string RUTPRODUCTOR { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public string CONTRATO { get; set; }
        public System.DateTime FECHAINICIOCONTRATO { get; set; }
        public System.DateTime FECHATERMINOCONTRATO { get; set; }
        public string ESTADOCONTRATO { get; set; }
        public Nullable<decimal> PROCESOID { get; set; }

        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
