//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PRODUCTO
    {
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name ="N° PRODUCTO")]
        public decimal IDPRODUCTO { get; set; }
        [Display(Name = "PRODUCTO")]
        public string DESCRIPCION { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        public Nullable<decimal> PRECIO { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        public Nullable<decimal> STOCK { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name = "N° ORDEN")]
        public Nullable<decimal> ORDEN_IDORDEN { get; set; }
        public string PRODUCTOR_RUTPRODUCTOR { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name = "N° PROCESO")]
        public Nullable<decimal> IDPROCESOVENTA { get; set; }
        [Display(Name = "ESTADO")]
        public string ESTADOPROCESO { get; set; }
        [Display(Name = "PROCESO")]
        public string TIPOVENTA { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        public Nullable<decimal> CANTIDAD { get; set; }
        public string CLIENTEINTERNO { get; set; }
        public decimal MONTOTOTALPRECIO { get; set; }

        public virtual ORDEN ORDEN { get; set; }
        public virtual PROCESOVENTA PROCESOVENTA { get; set; }
        public virtual PRODUCTOR PRODUCTOR { get; set; }
    }
}
