//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBASTA
    {
        public SUBASTA()
        {
            this.TRANSPORTISTA = new HashSet<TRANSPORTISTA>();
        }
    
        public decimal IDSUBASTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal PRECIO { get; set; }
        public decimal ORDEN_IDORDEN { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ORDEN ORDEN { get; set; }
        public virtual ICollection<TRANSPORTISTA> TRANSPORTISTA { get; set; }
    }
}
