//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SUBASTA
    {
        public SUBASTA()
        {
            this.TRANSPORTISTA = new HashSet<TRANSPORTISTA>();
        }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name = "N° SUBASTA")]
        public decimal IDSUBASTA { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime FECHA { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        [Display(Name = "N° PROCESO")]
        public Nullable<decimal> PROCESOVENTAID { get; set; }
    
        public virtual PROCESOVENTA PROCESOVENTA { get; set; }
        public virtual ICollection<TRANSPORTISTA> TRANSPORTISTA { get; set; }
    }
}
