//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string RUTUSUARIO { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public decimal PERFIL_IDPERFIL { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
    }
}
