//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtualWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public decimal IDVENTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<short> IMPUESTOADUANA { get; set; }
        public decimal COSTOTRANSPORTE { get; set; }
        public decimal COMISIONEMPRESA { get; set; }
        public decimal GASTOTOTAL { get; set; }
        public decimal GANANCIA { get; set; }
        public string ESTADO { get; set; }
        public string EMPRESA_RUTEMPRESA { get; set; }
        public decimal PROCESOVENTA_IDPROCESOVENTA { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual PROCESOVENTA PROCESOVENTA { get; set; }
    }
}
